<div class="border-b border-b-gray-900/10 lg:border-t lg:border-t-gray-900/5">
    <dl class="mx-auto grid max-w-7xl grid-cols-1 sm:grid-cols-4 lg:grid-cols-4 lg:px-2 xl:px-0">
<!-- Stats -->
<?php foreach ([
    'Pending' => $this->getPending(),
    'Processing' => $this->getProcessing(),
    'Success' => $this->getSuccess(),
    'Error' => $this->getError(),
] as $label => $values): ?>
    <div class="flex items-baseline flex-wrap justify-between gap-y-2 gap-x-4 border-t border-gray-900/5 px-4 py-10 sm:px-6 lg:border-t-0 xl:px-8 ">
        <dt class="font-medium leading-6 text-gray-500"><?=__('%1 Messages', $label)?></dt>
        <dd class="w-full flex-none text-3xl font-medium leading-10 tracking-tight text-gray-900"><?=$values->getSize()?></dd>
    </div>
<?php endforeach;?>
    </dl>
</div>